-- +migrate Up
-- ///////////////////
-- // ACCOUNT
-- ///////////////////
CREATE TABLE IF NOT EXISTS account
(
    id       UUID PRIMARY KEY     DEFAULT GEN_RANDOM_UUID(),
    username CITEXT      NOT NULL,
    email    CITEXT      NULL,
    disabled BOOLEAN     NOT NULL DEFAULT FALSE,
    
    created  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (email),
    UNIQUE (username),
    CONSTRAINT check__username_length CHECK (CHAR_LENGTH(username) BETWEEN 3 AND 255),
    CONSTRAINT check__email_length CHECK (CHAR_LENGTH(email) BETWEEN 6 AND 254)
);


-- +migrate StatementBegin
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'account_update_current_timestamp'
                         AND tgrelid = 'account'::regclass) THEN
            CREATE TRIGGER account_update_current_timestamp
                BEFORE UPDATE
                ON account
                FOR EACH ROW
            EXECUTE FUNCTION update_current_timestamp();
        END IF;
    END
$$;
-- +migrate StatementBegin

-- ///////////////////
-- // PROVIDERS
-- ///////////////////
CREATE TABLE IF NOT EXISTS provider
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       CITEXT      NOT NULL,
    type         CITEXT      NOT NULL,
    display_name TEXT        NOT NULL,
    category     VARCHAR(64) NOT NULL,
    disabled     BOOLEAN     NOT NULL DEFAULT FALSE,

    created      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(source, type),
    CONSTRAINT check__source_length CHECK (CHAR_LENGTH(source) BETWEEN 3 AND 120),
    CONSTRAINT check__type_length CHECK (CHAR_LENGTH(type) BETWEEN 3 AND 120),
    CONSTRAINT check__display_name_length CHECK (CHAR_LENGTH(display_name) BETWEEN 3 AND 255),
    CONSTRAINT check__category_length CHECK (CHAR_LENGTH(category) BETWEEN 3 AND 64)
);
CREATE INDEX IF NOT EXISTS provider__index_category ON provider (category);
-- +migrate StatementBegin
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'provider_update_current_timestamp'
                         AND tgrelid = 'provider'::regclass) THEN
            CREATE TRIGGER provider_update_current_timestamp
                BEFORE UPDATE
                ON provider
                FOR EACH ROW
            EXECUTE FUNCTION update_current_timestamp();
        END IF;
    END
$$;
-- +migrate StatementEnd

-- ///////////////////
-- // CREDENTIALS
-- ///////////////////
CREATE TABLE IF NOT EXISTS account_credentials
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential  TEXT        NOT NULL,
    account_id  UUID        NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    provider_id BIGINT      NOT NULL REFERENCES provider (id) ON DELETE RESTRICT,

    secret      TEXT        NOT NULL,
    secret_type TEXT        NOT NULL DEFAULT 'password', -- sha256, pem, opaque

    verified    BOOLEAN     NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMPTZ,

    disabled    BOOLEAN     NOT NULL DEFAULT FALSE,
    disabled_at TIMESTAMPTZ,

    created     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (provider_id, credential),
    UNIQUE (account_id, provider_id),
    CONSTRAINT check__verified_requires_timestamp
        CHECK ((verified = FALSE AND verified_at IS NULL) OR (verified = TRUE AND verified_at IS NOT NULL)),

    CONSTRAINT check__disabled_requires_timestamp
        CHECK ((disabled = FALSE AND disabled_at IS NULL) OR (disabled = TRUE AND disabled_at IS NOT NULL))
);
-- +migrate StatementBegin
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'account_credentials_update_current_timestamp'
                         AND tgrelid = 'account_credentials'::regclass) THEN
            CREATE TRIGGER account_credentials_update_current_timestamp
                BEFORE UPDATE
                ON account_credentials
                FOR EACH ROW
            EXECUTE FUNCTION update_current_timestamp();
        END IF;
    END
$$;
-- +migrate StatementEnd

-- ///////////////////
-- // ROLLBACK
-- ///////////////////

-- +migrate Down

DROP TABLE IF EXISTS account_credentials;
DROP TABLE IF EXISTS provider;
DROP TABLE IF EXISTS account;
