-- +migrate Up
-- -------------------
--   Admin ACCOUNT
-- -------------------
CREATE TABLE IF NOT EXISTS admin_account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id UUID        NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    disabled   BOOLEAN     NOT NULL DEFAULT FALSE,

    created    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- +migrate StatementBegin
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'admin_account_update_current_timestamp'
                         AND tgrelid = 'admin_account'::regclass) THEN
            CREATE TRIGGER admin_account_update_current_timestamp
                BEFORE UPDATE
                ON admin_account
                FOR EACH ROW
            EXECUTE FUNCTION update_current_timestamp();
        END IF;
    END
$$;
-- +migrate StatementEnd

CREATE TABLE permissions
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    service  TEXT        NOT NULL,
    resource TEXT        NOT NULL,
    action   TEXT        NOT NULL,

    created  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (service, resource, action)
);

CREATE TABLE account_permissions
(
    admin_account_id BIGINT      NOT NULL REFERENCES admin_account (id) ON DELETE CASCADE,
    permission_id    BIGINT      NOT NULL REFERENCES permissions (id) ON DELETE RESTRICT,

    created          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (admin_account_id, permission_id)
);


-- ///////////////////
-- // ROLLBACK
-- ///////////////////

-- +migrate Down
DROP TABLE IF EXISTS account_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS admin_account;
